### ISSUE TITLE
Automatically install peerDependencies

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/typedoc-auto-docs#12]
I'm installing packages with yarn v1 using `yarn add`.  This is not installing necessary peerDependencies, which causes docs rendering to fail.

The latest npm installs peerDependencies by default.  We can switch to that, or find some other way to auto-install peerdeps.

**Comment by keithlayne** [comment]
Does it do so recursively, or at least intelligently?  I'm for whatever works.

**Comment by cspotcode** [comment]
I think so?  I dunno, when I have time I'll try switching to `npm` and see if it works.  The `@yarnpkg/*` packages all have a peerDep on `@yarnpkg/core` so they should be a good test.

**Comment by cspotcode** [comment]
Fixed by #9.
