### ISSUE TITLE
[meta] pushing directly to `main` branch

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/typedoc-auto-docs#5]
I've been pushing directly to the `main` branch.  If that gets annoying, let me know and I'll start doing my work in topic branches and creating pull requests.

**Comment by keithlayne** [comment]
I was gonna use branches. I'm not annoyed unless you don't rebase :)

It might be a little funky with actions, I'll probably filter to my branch when fooling around, maybe even use a fake gh-pages branch until it's worked out.

**Comment by keithlayne** [comment]
I was also thinking of using a fork, but that might be needlessly compilcated when testing actions.

**Comment by cspotcode** [comment]
Ok, I just pushed something to main a few seconds ago, but I'll switch to using branches from here on.

**Comment by cspotcode** [comment]
For lack of a better place to mention what I pushed, I'll explain it here:

I updated the `yarn work` script to create a basic `index.html` and to push everything it renders to gh-pages.  Feel free to totally change, replace, modify how I'm doing that.  It's definitely sub-optimal.

https://typestrong.org/typedoc-auto-docs/

I wanted to start pushing to make it easier to share results: what's working, what's not, etc.

**Comment by cspotcode** [comment]
I also threw together a `db.ts` which can be used to store a SQLite database in git.  I have no idea if using sqlite is a good idea.  I'm sure you have some good ideas about how you want to store state.

**Comment by keithlayne** [comment]
SQLite is wonderful. I don't know if we *need* it's power, but I think it's reasonable. Most of the things that make me like it aren't really applicable here I don't think, but I'm fine with that.  Plus it may be obvious later that we need something like that.

Pretty sure though it can handle transactions from multiple processes and handle all kinds of things that are hard with files in general.  We may not need all that, but I can imagine it very easily.

**Comment by cspotcode** [comment]
I spoke too soon; I accidentally did *not* push that code to the `main` branch.

I have pushed it to a pull request: #10
